version: '3.8'

services:
  dev-environment:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    stdin_open: true
    tty: true
